LibraryManagement/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LibraryManagement.Models
{
    public class Book
    {
        [Key]
        public int BookID { get; set; }

        [DisplayName("Book Name"), Required(AllowEmptyStrings = false)]
        public string BookName { get; set; }

        [DisplayName("Author Name"), Required(AllowEmptyStrings = false)]
        public string AuthorName { get; set; }

        [DisplayName("Total Copies")]
        [Range(1, 1000, ErrorMessage ="Total Copies must be between 1 and 1000")]
        public int TotalCopiesNumber { get; set; }

        [DisplayName("Available Copies")]
        [Range(0, 1000, ErrorMessage = "Available Copies must be > 0")]
        public int AvailableCopiesNumber { get; set; }
        [DefaultValue(true)]
        public bool AvailableForBorrowing { get; set; }
    }
}

LibraryManagement/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryManagement.Models;
using LibraryManagement.Models.UnitOfWork;

namespace LibraryManagement.Controllers
{
    public class BooksController : Controller
    {
        private IUnitOfWork _uow;
        public BooksController()
        {
            _uow = new UnitOfWork();
        }
        public BooksController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Books
        public ActionResult Index()
        {
            return View(_uow.Books.List());
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookID,BookName,AuthorName,TotalCopiesNumber,AvailableCopiesNumber,AvailableForBorrowing")] Book book)
        {
            if (ModelState.IsValid)
            {
                if(book.AvailableCopiesNumber > book.TotalCopiesNumber)
                {
                    ModelState.AddModelError("", "Available Copies Must be Less than Total copies");
                    return View(book);
                }

                book.AvailableForBorrowing = book.AvailableCopiesNumber > 0 ? true : false;

                _uow.Books.Add(book);
                _uow.SaveAll();
                return RedirectToAction("Index");
            }

            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = _uow.Books.Find(id.Value);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookID,BookName,AuthorName,TotalCopiesNumber,AvailableCopiesNumber,AvailableForBorrowing")] Book book)
        {
            if (ModelState.IsValid)
            {
                if (book.AvailableCopiesNumber > book.TotalCopiesNumber)
                {
                    ModelState.AddModelError("", "Available Copies Must be Less than total copies");
                    return View(book);
                }
                
                book.AvailableForBorrowing = book.AvailableCopiesNumber == 0 ? false : true;
                _uow.Books.Edit(book);
                _uow.SaveAll();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = _uow.Books.Find(id.Value);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = _uow.Books.Find(id);
            if(book == null)
            {
                ModelState.AddModelError("", "Book Not Found");
                return View(book);
            }
            _uow.Books.Delete(book.BookID);
            _uow.SaveAll();
            return RedirectToAction("Index");
        }
    }
}

LibraryManagement/Controllers/BorrowingsController.cs
using System.Net;
using System.Web.Mvc;
using LibraryManagement.Models;
using LibraryManagement.Models.UnitOfWork;

namespace LibraryManagement.Controllers
{
    public class BorrowingsController : Controller
    {
        IUnitOfWork _uow;
        public BorrowingsController()
        {
            _uow = new UnitOfWork();
        }
        public BorrowingsController(IUnitOfWork uow)
        {
            _uow = uow;
        }
     
        // GET: Borrowings
        public ActionResult Index()
        {
            return View(_uow.Borrowings.List());
        }

        // GET: Borrowings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Borrowings borrowings = _uow.Borrowings.Find(id.Value);
            if (borrowings == null)
            {
                return HttpNotFound();
            }
            return View(borrowings);
        }

        // GET: Borrowings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Borrowings/Create
        [HttpPost]
        [ValidateAntiForgeryToken, ActionName("Create")]
        public ActionResult BorrowBook(Borrowings borrowings)
        {
            var bookName = borrowings.book.BookName;
            var book = _uow.Books.FirstOrDefault(b => b.BookName.Contains(bookName));
            if (book == null)
            {
                ModelState.AddModelError("", "Book Not Found");
                return View(borrowings);
            }

            var borrowerName = borrowings.borrower.BorrowerName;
            var borrower = _uow.Borrowers.FirstOrDefault(br => br.BorrowerName.Contains(borrowerName));
            if (borrower == null)
            {
                var newBorrower = new Borrower { BorrowerName = borrowerName };
                _uow.Borrowers.Add(newBorrower);
                borrowings.borrower = newBorrower;
            }
            else
            {
                borrowings.borrower = borrower;
            }

            if (!book.AvailableForBorrowing || book.AvailableCopiesNumber == 0)
            {
                ModelState.AddModelError("", "Book Not Available");
                return View(borrowings);
            }
            book.AvailableCopiesNumber -= 1;
            if (book.AvailableCopiesNumber == 0)
                book.AvailableForBorrowing = false;

            borrowings.book = book;
            _uow.Borrowings.Add(borrowings);
            _uow.SaveAll();

            return RedirectToAction("Index");
        }

        // GET: Borrowings/Edit/5
        public ActionResult Edit()
        {
            return View();
        }

        // POST: Borrowings/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken, ActionName("Edit")]
        public ActionResult ReturnBook(Borrowings borrowings)
        {
            var bookName = borrowings.book.BookName;
            var book = _uow.Books.FirstOrDefault(b => b.BookName.Contains(bookName));

            var borrowerName = borrowings.borrower.BorrowerName;
            var borrower = _uow.Borrowers.FirstOrDefault(bor => bor.BorrowerName.Contains(borrowerName));

            if (book == null || borrower == null)
            {
                ModelState.AddModelError("", "Not Accurate Info Book Name Or Borrower Name");
                return View(borrowings);
            }

            var borrowingRecord = _uow.Borrowings.FirstOrDefault(
                br => br.book.BookName.Contains(book.BookName)
                && br.DeliverdBack == false
                && br.borrower.BorrowerName == borrower.BorrowerName);

            if (borrowingRecord == null)
            {
                ModelState.AddModelError("", "Book Not Borrowed By This User Or has been Returned");
                return View(borrowings);
            }

            borrowingRecord.DeliverdBack = true;

            book.AvailableCopiesNumber += 1;
            book.AvailableForBorrowing = true;

            _uow.SaveAll();
            return RedirectToAction("Index");
        }

        // GET: Borrowings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Borrowings borrowings = _uow.Borrowings.Find(id.Value);
            if (borrowings == null)
            {
                return HttpNotFound();
            }
            return View(borrowings);
        }

        // POST: Borrowings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Borrowings borrowings = _uow.Borrowings.Find(id);
            if (borrowings == null)
                return HttpNotFound();
            _uow.Borrowings.Delete(borrowings.BorrowingID);
            _uow.SaveAll();
            return RedirectToAction("Index");
        }
    }
}

LibraryManagement/Views/Books/Create.cshtml
@model LibraryManagement.Models.Book

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BookName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalCopiesNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalCopiesNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalCopiesNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableCopiesNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AvailableCopiesNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AvailableCopiesNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableForBorrowing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AvailableForBorrowing)
                    @Html.ValidationMessageFor(model => model.AvailableForBorrowing, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LibraryManagement/Views/Books/Delete.cshtml
@model LibraryManagement.Models.Book

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalCopiesNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalCopiesNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableCopiesNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableCopiesNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableForBorrowing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableForBorrowing)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LibraryManagement/Views/Books/Edit.cshtml
@model LibraryManagement.Models.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BookID)

        <div class="form-group">
            @Html.LabelFor(model => model.BookName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalCopiesNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalCopiesNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalCopiesNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableCopiesNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AvailableCopiesNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AvailableCopiesNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableForBorrowing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AvailableForBorrowing)
                    @Html.ValidationMessageFor(model => model.AvailableForBorrowing, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LibraryManagement/Views/Books/Index.cshtml
@model IEnumerable<LibraryManagement.Models.Book>

@{
    ViewBag.Title = "Index";
}

<h2>List of all Books</h2>
<br />

<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BookName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuthorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalCopiesNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AvailableCopiesNumber)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalCopiesNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvailableCopiesNumber)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.BookID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.BookID })
            </td>
        </tr>
    }
<tr>
    <th>
        @Html.ActionLink("Borrow a Book", "Create", "Borrowings",null, new { @class = "btn btn-success" })
    </th>
    <th></th>
    <th>
        @Html.ActionLink("Return a Book", "Edit", "Borrowings", null, new { @class = "btn btn-warning" })
    </th>
    <th></th>
    <th>
        @Html.ActionLink("Add New Book", "Create", null, new { @class = "btn btn-primary" })
    </th>
</tr>
</table>